print("Script loading... 0/4")
wait(1)
loadstring(game:HttpGet("https://raw.githubusercontent.com/JoeGotElected/SA-FYTedit/UI/spychat.lua"))()
print("1/4")
loadstring(game:HttpGet("https://raw.githubusercontent.com/JoeGotElected/SA-FYTedit/UI/mainExploit.lua"))()
print("2/4")
loadstring(game:HttpGet("https://raw.githubusercontent.com/JoeGotElected/SA-FYTedit/UI/infyield.lua"))()
print("3/4")
loadstring(game:HttpGet("https://raw.githubusercontent.com/JoeGotElected/SA-FYTedit/UI/wedontcare.lua"))()
print("4/4")
wait(1)
print("all code has been launched succsesfully!")